[build]
cmds = ["composer install --no-dev --optimize-autoloader", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t public/"
