services:
  - type: web
    name: prm-api
    env: php
    plan: free
    buildCommand: composer install && php artisan key:generate
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    autoDeploy: true
    branch: main